config/routes.rb
Forgeos::Cms::Engine.routes.draw do
  namespace :admin do
    %w(page block).each do |model|
      match "/import/create_#{model}" => "import#create_#{model}", :as => "import_create_#{model}"
    end


    resources :actualities do
      member do
        post :activate
      end
    end
    resources :static_content_blocks do
      member do
        get :duplicate
      end
    end

    resources :blocks, :controller => 'static_content_blocks'

    resources :pages do
      member do
        post :activate
        get :duplicate
      end
      collection do
        post :url
      end
      resources :blocks, :controller => 'static_content_blocks', :except => [:show, :index] do
         member do
           post :link
           delete :unlink
        end
      end
      resources :widgets, :except => [:index]
      resources :wactualities, :except => [:show, :index]
      resources :carousels, :except => [:show, :index]
    end

    resources :newsletters
    # modules and widgets
    resources :widgets, :only => [:index]
    resources :carousels do
      member do
        get :duplicate
      end
    end
    resources :widget_actualities do
      member do
        get :duplicate
      end
    end
    resources :link_page do
      member do
        get :duplicate
      end
    end
    resources :widget_faqs do
      member do
        get :duplicate
      end
    end

    resources :menus do
      member do
        get :duplicate
        post :activate
      end
    end

    # categories
    %w(page static_content widget).each do |category|
      resources "#{category}_categories", :controller => 'categories', :type => "#{category}_category"
    end
  end
end

app/models/menu.rb
class Menu < ActiveRecord::Base
  validates :name, :presence => true
  validates :single_key, :if => Proc.new {|c| c.single_key}, :uniqueness => true

  has_and_belongs_to_many :categories,
    :readonly => true,
    :join_table => 'categories_elements',
    :foreign_key => 'element_id',
    :association_foreign_key => 'category_id',
    :class_name => 'MenuCategory'

  has_many :menu_links,
    :dependent => :destroy,
    :order => 'position'
  accepts_nested_attributes_for :menu_links, :allow_destroy => true

  define_index do
    indexes name, :sortable => true
  end

  def activate
    self.update_attribute('active', !self.active)
  end

  def clone
    menu = super
    menu.menu_links = self.menu_links.collect(&:clone)
    return menu
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  translates :title, :url
  define_translated_index :title, :url
  acts_as_taggable_on :tags

  attr_accessor :page_urls

  validates :title, :url, :presence => true
  validates :single_key, :if => Proc.new {|c| c.single_key}, :uniqueness => true

  has_one :meta_info,
    :as => :target,
    :dependent => :destroy
  accepts_nested_attributes_for :meta_info

  has_many :page_cols,
    :dependent => :destroy
  has_many :blocks,
    :through => :page_cols
  accepts_nested_attributes_for :page_cols

  has_many :viewed_counters,
    :as => :element,
    :class_name => 'PageViewedCounter',
    :dependent => :destroy
  has_many :menu_links,
    :as => :target

  has_and_belongs_to_many :categories,
    :readonly => true,
    :join_table => 'categories_elements',
    :foreign_key => 'element_id',
    :association_foreign_key => 'category_id'
  has_and_belongs_to_many :linked_pages,
    :class_name => 'Page',
    :association_foreign_key => 'linked_page_id',
    :foreign_key => 'page_id',
    :join_table => 'pages_links'

  before_destroy :check_has_no_single_key,
    :keep_page_translated_urls


  def name
    self.title
  end

  def page_urls
    destroyed? ? super : translations.collect(&:url)
  end

  def min_cols_by_page
    1
  end

  def activate
    # set publication date if page changes from inactive to active
    self.published_at = Time.now unless self.active

    # update active status
    self.update_attribute('active', !self.active)
  end

  def clone
    page = super
    page.meta_info = meta_info.clone if meta_info
    page.translations = translations.clone unless translations.empty?
    page.page_cols = page_cols.map(&:clone)
    page.tags = tags
    return page
  end

  private
  # if the page contains a single_key, it can not be destroyed
  def check_has_no_single_key
    unless self.single_key.blank?
      errors.add(:the_page, :has_single_key)
      return false
    end
  end

  def keep_page_translated_urls
    self.page_urls = translations.collect(&:url)
  end
end

app/models/static_content_block.rb
class StaticContentBlock < Block
end

app/controllers/admin/static_content_blocks_controller.rb
class Admin::StaticContentBlocksController < Admin::BaseController
  cache_sweeper :page_sweeper, :only => [:create, :update, :destroy, :link, :unlink]
  before_filter :new_block, :only => [:new, :create]
  before_filter :get_block, :only => [:show, :edit, :update, :destroy, :duplicate, :link, :unlink]
  before_filter :get_page, :only => [:destroy, :link, :unlink]
  before_filter :get_pages_and_categories, :only => [:index, :new, :create, :edit, :update, :duplicate]

  def index
    respond_to do |format|
      format.html
      format.json do
        sort
        render :layout => false
      end
    end
  end

  def show
  end

  def new
  end

  def duplicate
    @static_content_block = @static_content_block.clone
    render :action => 'new'
  end

  def edit
  end

  def create
    if @static_content_block.save
      flash[:notice] = I18n.t('block.create.success').capitalize
      redirect_to([forgeos_cms, :edit, :admin, @static_content_block])
    else
      flash[:error] = I18n.t('static_content_block.create.failed').capitalize
      render :action => "new"
    end
  end

  def update
    if @static_content_block.update_attributes(params[:static_content_block])
      flash[:notice] = I18n.t('static_content_block.update.success').capitalize
    else
      flash[:error] = I18n.t('static_content_block.update.failed').capitalize
    end
    render :action => "edit"
  end

  def destroy
    if @static_content_block.destroy
      flash[:notice] = I18n.t('static_content_block.destroy.success').capitalize
    else
      flash[:error] = I18n.t('static_content_block.destroy.failed').capitalize
    end
    respond_to do |wants|
      wants.html do
        redirect_to([forgeos_cms, :admin, :static_content_blocks])
      end
      wants.js
    end
  end

  def link
    unless @static_content_block.linked_with? @page
      if @static_content_block.link_with @page
        flash[:notice] = I18n.t('static_content_block.link.create.success').capitalize
      else
        flash[:error] = I18n.t('static_content_block.link.create.failed').capitalize
      end
    else
      if @static_content_block.unlink_with @page
        flash[:notice] = I18n.t('static_content_block.link.destroy.success').capitalize
      else
        flash[:error] = I18n.t('static_content_block.link.destroy.success').capitalize
      end
    end

    if request.xhr?
      return render :text => true
    else
      return redirect_to(:back)
    end
  end

  def unlink
    if @page.blocks.delete(@static_content_block)
      @page.blocks.reset_positions
      flash[:notice] = I18n.t('static_content_block.link.destroy.success').capitalize
    else
      flash[:notice] = I18n.t('static_content_block.link.destroy.success').capitalize
    end

    render :nothing => true
  end

private

  def new_block
    @static_content_block = StaticContentBlock.new(params[:static_content_block])
  end

  def get_block
    unless @static_content_block = Block.find_by_id(params[:id])
      flash[:error] = I18n.t('static_content_block.not_exist').capitalize
      return redirect_to(@page ? [forgeos_cms, :admin, :static_content_blocks, @page] : [forgeos_cms, :admin, :blocks])
    end
    return redirect_to([forgeos_cms, :edit, :admin, @static_content_block]) unless @static_content_block.is_a?(StaticContentBlock)
  end

  def get_page
    @page = Page.find_by_id(params[:page_id])
  end

  def get_pages_and_categories
    @page_categories = PageCategory.find_all_by_parent_id(nil, :group => 'category_id', :joins => :translations, :order => 'name')
    @pages = Page.all(:include => :categories, :conditions => { :categories_elements => { :category_id => nil }})
  end

  def link_and_redirect_to_page
    @page.blocks << @static_content_block
    @page.blocks.reset_positions

    if @static_content_block.save
      return redirect_to([forgeos_cms, :admin, :static_content_blocks, @page])
    else
      @static_content_block.destroy
      flash[:notice] = nil
      flash[:error] = @static_content_block.errors
      return
    end
  end

  def sort
    columns = %w(blocks.id block_translations.title count(pages.id) blocks.id)
    per_page = params[:iDisplayLength].to_i
    offset =  params[:iDisplayStart].to_i
    page = (offset / per_page) + 1
    order_column = params[:iSortCol_0].to_i
    order = "#{columns[order_column]} #{params[:sSortDir_0].upcase}"

    conditions = {}
    includes = []
    group_by = []
    options = { :page => page, :per_page => per_page }

    if params[:category_id]
      conditions[:categories_elements] = { :category_id => params[:category_id] }
      includes << :categories
    end

    if order_column == 2
      includes << :pages
      group_by << 'blocks.id'
    end

    options[:conditions] = conditions unless conditions.empty?
    options[:include] = includes unless includes.empty?
    options[:group] = group_by.join(', ') unless group_by.empty?
    # FIXME - order with globalize
    options[:order] = order unless order.squeeze.blank?

    joins = []
    joins << :translations

    if params[:sSearch] && !params[:sSearch].blank?
      options[:index] = "block_#{ActiveRecord::Base.locale}_core"
      options[:order_sql] = options.delete(:order)
      options[:star] = true
      @blocks = StaticContentBlock.search(params[:sSearch],options)
    else
      options[:joins] = joins
      @blocks = StaticContentBlock.paginate(options)
    end
  end
end

app/views/admin/static_content_blocks/_form.html.haml
= render :partial => 'admin/menus/lang_switcher'
= render :partial => 'admin/blocks/tabs'
= form_for [forgeos_cms, :admin, static_content_block], :html => { "data-object_name" => static_content_block.class.model_name.singular, :id => 'wrap' } do |f|
  .backgrounds.big-header
    = f.text_field :title, :class => 'field_name'
    .interact-links
      = submit_tag I18n.t('save').capitalize, :class => 'backgrounds interact-button'
      = I18n.t('or')
      = link_to I18n.t('cancel').capitalize, forgeos_cms.admin_static_content_blocks_path, :class => 'back-link'

  #content.grid_12.alpha.omega
    .inner-content
      %h2.description
        = I18n.t('description').capitalize
      = f.text_area :content, :class => 'mceEditor', :cols => 85

  #right-sidebar.grid_4.alpha.omega
    .step
      -# = link_to I18n.t('static_content_block.preview').capitalize, '#', :class => 'small-icons preview'
      = content_tag :span, I18n.t('static_content_block.preview').capitalize, :class => 'small-icons preview disabled'
      - unless static_content_block.new_record?
        = link_to I18n.t('static_content_block.duplicate').capitalize, forgeos_cms.duplicate_admin_static_content_block_path(static_content_block), :class => 'small-icons duplicate'
        = link_to I18n.t('static_content_block.delete').capitalize, [forgeos_cms, :admin, static_content_block], :confirm => I18n.t('static_content_block.destroy.confirm').capitalize, :method => :delete, :class => 'small-icons delete'

    #blocks_create.step.open
      %a.small-icons.step-title{ :href => "#" }
        = "#{I18n.t('static_content_block.link.create.action').capitalize} :"
      = hidden_field_tag 'static_content_block[page_col_ids][]'
      #association-static-content-page-tree.inner-step
        %ul
          = render :partial => 'admin/blocks/associated_pages', :locals => { :categories => @page_categories, :pages => @pages, :block => static_content_block, :element_id => 'static_content_block' }
      .clear
    #blocks_associated_to.step.open
      %a.small-icons.step-title{ :href => "#" }
        = "#{I18n.t('folder.associated_to').capitalize} :"
      = hidden_field_tag 'static_content_block[category_ids][]'
      #association-static-content-tree.inner-step
        %ul
          = render :partial => 'admin/categories/associated_elements', :locals => { :association_id => 'category_ids', :element => static_content_block, :category_ids => static_content_block.category_ids, :categories => StaticContentCategory.find_all_by_parent_id(nil) }
      .clear
  .clear

app/views/admin/static_content_blocks/destroy.js.erb
removedataTablesRow('#<%= polymorphic_html_id @static_content_block, 'destroy' -%>');

app/views/admin/static_content_blocks/edit.html.haml
= render :partial => 'form', :locals => { :static_content_block => @static_content_block }

app/views/admin/static_content_blocks/index.html.haml
= render :partial => 'admin/blocks/tabs'
= render :partial => 'admin/sidebars/left_sidebar', :locals => { :icon_class => 'blocks', :sidebar_title => 'block.all', :tree_id =>'block-tree' }
#content.grid_12.alpha.omega
  .backgrounds.header
    = link_to content_tag(:span,I18n.t('static_content_block.create.action').capitalize, :class=>'big-icons create-block'), forgeos_cms.new_admin_block_path, :class=>'backgrounds action-button'
    #search.right
      = link_to content_tag(:span, I18n.t('search').capitalize, :class => 'small-icons search-span'), '#', :class => 'small-icons left search-link'
    .backgrounds.search-form
  .content-background
  %table#table.datatable.draggable_rows

= dataTables_tag :url => forgeos_cms.admin_blocks_path(:format => :json), :columns => ["{'sClass': 'image_product_td', 'bSearchable':false,'bSortable':false}","{'sTitle':'#{I18n.t 'static_content_block.name'}'}","{'sTitle':'#{I18n.t :linked_to}','bSearchable':false}","{'sClass':'actions-td','bSearchable':false,'bSortable':false}"]
.lightbox-container
  .pages-tree
    %ul
      = render :partial => 'admin/categories/list_pages', :locals => { :categories => @page_categories, :pages => @pages }

app/views/admin/static_content_blocks/index.json.erb
<%
  output = {
    :sEcho => params[:sEcho],
    :iTotalRecords => @blocks.total_entries || 0,
    :iTotalDisplayRecords => @blocks.size,
    :aaData => @blocks.collect do |block|
      nb_pages = block.page_cols.count
      [
        content_tag(:div, content_tag(:div, content_tag(:span, '', :class => 'small-icons block'), :class=>'image'), :id => polymorphic_html_id(block), :class => 'some-variants plus'),
        content_tag(:div, link_to(block.title, [forgeos_cms, :edit, :admin, block]), :class => 'page-name'),

        content_tag(:span,"#{nb_pages.to_s} #{I18n.t('page', :count => nb_pages)}", :class=>'linked_to'),

        link_to('', forgeos_cms.duplicate_admin_static_content_block_path(block), :class => 'small-icons duplicate-link') +
        link_to('', [forgeos_cms, :edit, :admin, block], :class => 'small-icons edit-link') +
        link_to('', [forgeos_cms, :admin, block],
          :remote => true,
          :method => :delete,
          :confirm => I18n.t('static_content_block.destroy.confirm').capitalize,
          :class => 'small-icons destroy-link',
          :id => polymorphic_html_id(block, 'destroy')
        )
      ]
    end
  }
-%>
<%= raw output.to_json -%>

app/views/admin/static_content_blocks/new.html.haml
= render :partial => 'form', :locals => { :static_content_block => @static_content_block, :page_id => params[:page_id] }

app/views/admin/static_content_blocks/show.html.haml
= render :partial => 'admin/menus/lang_switcher'
= render :partial => 'admin/blocks/tabs'
#wrap
  .backgrounds.big-header
    %h1
      = @static_content_block.title
    .interact-links
      = link_to I18n.t('static_content_block.update.action', :count => 1).capitalize, [forgeos_cms, :edit, :admin, @static_content_block ], :class => 'backgrounds interact-button'
      = I18n.t('or')
      = link_to I18n.t('static_content_block.back').capitalize, forgeos_cms.admin_static_content_blocks_path, :class => 'back-link'
  #content.grid_16.alpha.omega
    .grid_12.alpha
      .inner-content
        .block-content
          = @static_content_block.content
    #right-sidebar.grid_4.omega
      .step
        -# = link_to I18n.t('static_content_block.preview').capitalize, '#', :class => 'small-icons preview'
        = content_tag :span, I18n.t('static_content_block.preview').capitalize, :class => 'small-icons preview disabled'
        = link_to I18n.t('static_content_block.duplicate').capitalize, forgeos_cms.duplicate_admin_static_content_block_path(@static_content_block), :class => 'small-icons duplicate'
        = link_to I18n.t('static_content_block.delete').capitalize, [forgeos_cms, :admin, @static_content_block], :confirm => I18n.t('static_content_block.destroy.confirm').capitalize, :method => :delete, :class => 'small-icons delete'
        .clear
    .clear