config/routes.rb
Forgeos::Cms::Engine.routes.draw do
  namespace :admin do
    %w(page block).each do |model|
      match "/import/create_#{model}" => "import#create_#{model}", :as => "import_create_#{model}"
    end


    resources :actualities do
      member do
        post :activate
      end
    end
    resources :static_content_blocks do
      member do
        get :duplicate
      end
    end

    resources :blocks, :controller => 'static_content_blocks'

    resources :pages do
      member do
        post :activate
        get :duplicate
      end
      collection do
        post :url
      end
      resources :blocks, :controller => 'static_content_blocks', :except => [:show, :index] do
         member do
           post :link
           delete :unlink
        end
      end
      resources :widgets, :except => [:index]
      resources :wactualities, :except => [:show, :index]
      resources :carousels, :except => [:show, :index]
    end

    resources :newsletters
    # modules and widgets
    resources :widgets, :only => [:index]
    resources :carousels do
      member do
        get :duplicate
      end
    end
    resources :widget_actualities do
      member do
        get :duplicate
      end
    end
    resources :link_page do
      member do
        get :duplicate
      end
    end
    resources :widget_faqs do
      member do
        get :duplicate
      end
    end

    resources :menus do
      member do
        get :duplicate
        post :activate
      end
    end

    # categories
    %w(page static_content widget).each do |category|
      resources "#{category}_categories", :controller => 'categories', :type => "#{category}_category"
    end
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  translates :title, :url
  define_translated_index :title, :url
  acts_as_taggable_on :tags

  attr_accessor :page_urls

  validates :title, :url, :presence => true
  validates :single_key, :if => Proc.new {|c| c.single_key}, :uniqueness => true

  has_one :meta_info,
    :as => :target,
    :dependent => :destroy
  accepts_nested_attributes_for :meta_info

  has_many :page_cols,
    :dependent => :destroy
  has_many :blocks,
    :through => :page_cols
  accepts_nested_attributes_for :page_cols

  has_many :viewed_counters,
    :as => :element,
    :class_name => 'PageViewedCounter',
    :dependent => :destroy
  has_many :menu_links,
    :as => :target

  has_and_belongs_to_many :categories,
    :readonly => true,
    :join_table => 'categories_elements',
    :foreign_key => 'element_id',
    :association_foreign_key => 'category_id'
  has_and_belongs_to_many :linked_pages,
    :class_name => 'Page',
    :association_foreign_key => 'linked_page_id',
    :foreign_key => 'page_id',
    :join_table => 'pages_links'

  before_destroy :check_has_no_single_key,
    :keep_page_translated_urls


  def name
    self.title
  end

  def page_urls
    destroyed? ? super : translations.collect(&:url)
  end

  def min_cols_by_page
    1
  end

  def activate
    # set publication date if page changes from inactive to active
    self.published_at = Time.now unless self.active

    # update active status
    self.update_attribute('active', !self.active)
  end

  def clone
    page = super
    page.meta_info = meta_info.clone if meta_info
    page.translations = translations.clone unless translations.empty?
    page.page_cols = page_cols.map(&:clone)
    page.tags = tags
    return page
  end

  private
  # if the page contains a single_key, it can not be destroyed
  def check_has_no_single_key
    unless self.single_key.blank?
      errors.add(:the_page, :has_single_key)
      return false
    end
  end

  def keep_page_translated_urls
    self.page_urls = translations.collect(&:url)
  end
end

app/views/admin/pages/_block_popup.html.haml
.lightbox-container
  #sub-links
    %ul
      %li= link_to I18n.t('static_content_block', :count => 1).capitalize, '#', :class => 'static-tab selected'
      %li= link_to I18n.t('widget', :count => 2).capitalize, '#', :class => 'widget-tab'
  #blocks
    .blocks-tree
      - unless @static_blocks.blank?
        %ul
          = render :partial => 'admin/categories/list_blocks', :locals => { :page => page, :categories => @static_block_categories, :blocks => @static_blocks }
    .clear
    = link_to I18n.t('page.block.add').capitalize, '#', :class => 'small-icons add-link'
  #widgets.hidden
    .blocks-tree
      - unless @widgets.blank?
        %ul
          = render :partial => 'admin/categories/list_blocks', :locals => { :page => page, :categories => @widget_categories, :blocks => @widgets }
    .clear
    = link_to I18n.t('page.widget.add').capitalize, '#', :class => 'small-icons add-link'

app/views/admin/pages/_blocks.html.haml
- i = 0
= f.fields_for :page_cols do |page_col|
  .fieldset.open
    %h2= t("page_col_#{i}")
    .option-panel-content
      %a#add-block.backgrounds.static-content.action-button{ :href => "#" }
        %span.big-icons
          = t('page.block.add').capitalize
      %a#add-widget.backgrounds.widget-content.action-button{ :href => "#" }
        %span.big-icons
          = t('page.widget.add').capitalize
      .clear
      .nested_sortable
        = hidden_field_tag "page[page_cols_attributes][#{i}][block_ids][]"
        - page_col.object.blocks.each do |block|
          .block-container
            %span.block-type
              %span.handler
                %span.inner
              %span
                = block.class.model_name.human.capitalize
            %span.block-name
              = block.title.capitalize unless block.title.nil?

            = link_to('', [forgeos_cms, :edit, :admin, block], :popup => true, :class => 'small-icons edit-link')
            = link_to '', '#', :class => 'big-icons gray-destroy'
            = hidden_field_tag "page[page_cols_attributes][#{i}][block_ids][]", block.id
        .clear
    - i = i+1

app/views/admin/pages/_codes.html.haml
.grid_15
  %p.tool-tip-settings
    = t(:paste_code)
  .grid_8.alpha
    %p
      %span
        = t(:page_code)
        \:
      %br
      = f.text_area :page_code, :class => 'text', :cols => 60, :rows => 7
  .tool-tip-settings.grid_6.omega
    = t(:page_code_explain)
  .clear
  .grid_8.alpha
    %p
      %span
        = t(:header_code)
        \:
      %br
      = f.text_area :header_code, :class => 'text', :cols => 60, :rows => 7
  .tool-tip-settings.grid_6.omega
    = t(:header_code_explain)
  .clear
  .grid_8.alpha
    %p
      %span
        = t(:bottom_code)
        \:
      %br
      = f.text_area :bottom_code, :class => 'text', :cols => 60, :rows => 7
  .tool-tip-settings.grid_6.omega
    = t(:bottom_code_explain)
  .clear

app/views/admin/pages/_form.html.haml
= render :partial => 'admin/menus/lang_switcher'
= render :partial => 'tabs'
= form_for [forgeos_cms, :admin, page], :html => { "data-object_name" => page.class.model_name.singular, :id => 'wrap' } do |f|
  #blocks-header.ui-tabs.ui-widget.ui-widget-content.ui-corner-all
    %ul.ui-tabs-nav.ui-helper-reset.ui-helper-clearfix.ui-widget-header.ui-corner-all
      %li.ui-state-default.ui-corner-top.ui-tabs-selected.ui-state-active= link_to t(:general), '#general', :class => 'selected'
      %li.ui-state-default.ui-corner-top= link_to t(:block,:count => 2), '#blocks'
      %li.ui-state-default.ui-corner-top= link_to t(:seo), '#seo'
      %li.ui-state-default.ui-corner-top= link_to t(:codes), '#codes'
    .backgrounds.big-header
      = f.text_field :title, :class => 'field_name big_orange_input'
      .interact-links
        = Forgeos_save_buttons [forgeos_cms, :admin, :pages]
    #general
      = render :partial => 'general', :locals => {:f => f, :page => page }
      .clear
    #blocks
      = render :partial => 'blocks', :locals => { :f => f, :page => page }
    #seo{:style => 'padding: 0'}
      = render :partial => 'seo', :locals => { :f => f, :page => page }
    #codes
      = render :partial => 'codes', :locals => { :f => f, :page => page }
    .clear
= render :partial => 'block_popup', :locals => { :page => page }

app/views/admin/pages/_general.html.haml
.grid_12.alpha
  .inner-content
    - i = 0
    = f.fields_for :page_cols do |page_col|
      = page_col.label :content, t("page_col_#{i}")
      = page_col.text_area :content, :class => 'mceEditor', :cols => 85
      .clear
      - i = i+1

#right-sidebar.grid_4.omega
  .step.status.open
    %div
      - status = [[I18n.t('page.published'), 'published'], [I18n.t('page.draft'), 'draft']]
      = select_tag :status, options_for_select(status, page.active ? 'published' : 'draft'), :class => 'customize published'
    .clear
    %p
      - unless page.new_record? or !page.active or page.published_at.nil?
        = I18n.t('page.published_on').capitalize
        %span.last-date
          = page.published_at.to_date if page.published_at
          /
            %br
            by TODO
            %em
              Quentin Tousart
  .step
    -# = link_to I18n.t('page.preview').capitalize, '#', :class => 'small-icons preview'
    = content_tag :span, I18n.t('page.preview').capitalize, :class => 'small-icons preview disabled'
    - unless page.new_record?
      = link_to I18n.t('page.duplicate').capitalize, [forgeos_cms, :duplicate, :admin, page], :class => 'small-icons duplicate'
      = link_to I18n.t('page.delete').capitalize, [forgeos_cms, :admin, page], :confirm => I18n.t('page.destroy.confirm').capitalize, :method => :delete, :class => 'small-icons delete'
  /
    #history_step.step.disabled
      %a.small-icons.step-title{ :href => "#" }= I18n.t('page.modification_history').capitalize
      .inner-step
        %p
          Modified on
          %span.last-date
            12/11/2009
          %br
          by
          %em
            Quentin Tousart
        %p
          Created on 11/11/2009
          %br
          by
          %em
            Quentin Tousart
    .step.disabled
      %a.small-icons.step-title{ :href => "#" }
        Graphic template
      .inner-step.glossy
        %select{ :name => "design" }
          %option{ :selected => "selected", :value => "default" }
            Corporate blue design
          %option{ :value => "no" }
            Corporate green design
      .clear

app/views/admin/pages/_page_url.html.haml
= f.text_field :url

app/views/admin/pages/_seo.html.haml
.grid_12
  .fieldset.open
    %h3.permalink
      = t('permalink').capitalize
      \:
    .option-panel-content
      = render :partial => 'page_url', :locals => {:f => f}
  .fieldset.open
    %h3= t(:meta_info,:count => 1)
    .option-panel-content.meta
      - f.object.build_meta_info unless f.object.meta_info
      = f.fields_for :meta_info do |meta_info|
        %p
          %span
            = t(:title).capitalize
            \:
          %br
          = meta_info.text_field :title, :class => 'text', :size => 90
        %p
          %span
            = t(:description).capitalize
            \:
          %br
          = meta_info.text_area :description, :class => 'text', :cols => 90, :rows => 5
        %p
          %span
            = t(:keyword, :count => 2).capitalize
            \:
          %br
          = meta_info.text_area :keywords, :class => 'text', :cols => 90, :rows => 5

app/views/admin/pages/_tabs.html.haml
%ul.ui-tabs-nav.ui-helper-reset.ui-helper-clearfix.ui-widget-header.ui-corner-all
  %li.ui-state-default.ui-corner-top.ui-tabs-selected.ui-state-active= link_to I18n.t('page', :count => 2).capitalize, '#content'
  %li.ui-state-default.ui-corner-top= link_to I18n.t('block', :count => 2).capitalize, [forgeos_cms, :admin, :static_content_blocks]
  %li.ui-state-default.ui-corner-top= link_to I18n.t('navigation').capitalize, [forgeos_cms, :admin, :menus]
  %li.ui-state-default.ui-corner-top= link_to I18n.t('actuality', :count => 2).capitalize, [forgeos_cms, :admin, :actualities]

app/views/admin/pages/edit.html.haml
= render :partial => 'form', :locals => { :page => @page }

app/views/admin/pages/edit_blocks.html.erb
<%= render :partial => 'top_links', :locals => { :page => @page } %>

<h1><%= I18n.t('block.update.action', :count => 2).capitalize %></h1>

<% if @page %>
  <h2><%= I18n.t('page', :count => 1).capitalize %> <%= @page.title %></h2>

  <h3>
    <%= link_to I18n.t('block.create.action').capitalize, { :controller => 'admin/blocks', :action => 'create', :page_id => @page.id } %>
  </h3>

  <div id="edit_blocks">
    <table id="table">
      <thead>
        <tr>
          <th><%= I18n.t('title').capitalize %></th>
          <th><%= I18n.t('other_linked_pages').capitalize %></th>
          <th><%= I18n.t('action', :count => 2).capitalize %></th>
        </tr>
      </thead>
      
      <tbody>
        <% unless @page.blocks.nil? or @page.blocks.blank? %>
          <% @page.blocks.each do |block| %>
            <tr class="<%= cycle('even', 'odd') %>">
              <td><%= link_to block.title, :controller => 'admin/blocks', :action => 'show', :id => block.id %></td>
              <td><%= block.pages.size - 1 %></td>
              <td>
                <%= link_to I18n.t('edit').capitalize, :controller => 'admin/blocks', :action => 'edit', :id => block.id, :page_id => @page.id %>
                -
                <%= link_to I18n.t('move_up').capitalize, :action => 'order_blocks', :id => @page.id, :block_id => block.id, :order => 'up' %>
                -
                <%= link_to I18n.t('move_down').capitalize, :action => 'order_blocks', :id => @page.id, :block_id => block.id, :order => 'down' %>
                -
                <%= link_to I18n.t('unlink').capitalize, { :action => 'unlink_block', :id => @page.id, :block_id => block.id }, :confirm => I18n.t('page.unlink_block.confirm').capitalize %>
                -
                <%= link_to I18n.t('delete').capitalize, { :controller => 'admin/blocks', :action => 'delete', :id => block.id, :page_id => @page.id }, :confirm => I18n.t('block.destroy.confirm_associated').capitalize %>
              </td>
            </tr>
          <% end %>

        <% else %>
          <tr> 
            <td colspan="3"><%= I18n.t('block.none').capitalize %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

<%= javascript_tag "$($('#table').dataTable({
        'aoColumns': [
            null,
            null,
            { 'bSearchable': false, 'bSortable': false }
        ],
        'bSort': false,
        'oLanguage': { 
        'sProcessing':'#{I18n.t('jquery.dataTables.oLanguage.sProcessing')}',
        'sLengthMenu':'#{I18n.t('jquery.dataTables.oLanguage.sLengthMenu')}',
        'sZeroRecords':'#{I18n.t('jquery.dataTables.oLanguage.sZeroRecords')}',
        'sInfo':'#{I18n.t('jquery.dataTables.oLanguage.sInfo')}',
        'sInfoEmpty':'#{I18n.t('jquery.dataTables.oLanguage.sInfoEmpty')}',
        'sSearch':'#{I18n.t('jquery.dataTables.oLanguage.sSearch')}' }
    }
))" %>

app/views/admin/pages/index.html.haml
= render :partial => 'tabs'
= render :partial => 'admin/sidebars/left_sidebar', :locals => {:icon_class => 'pages', :sidebar_title => 'page.all', :tree_id =>'page-tree'}

#content.grid_12.alpha.omega
  .backgrounds.header
    = link_to content_tag(:span,I18n.t('page.create.action').capitalize, :class=>'big-icons create-page'), [forgeos_cms, :new, :admin, :page], :class=>'backgrounds action-button'
    #search.right
      = link_to content_tag(:span, I18n.t('search').capitalize, :class => 'small-icons search-span'), '#', :class => 'small-icons left search-link'
    .backgrounds.search-form
  .content-background
  %table#table.datatable.draggable_rows

= dataTables_tag :url => forgeos_cms.admin_pages_path(:format => :json), :columns => ["{'bSearchable':false,'bSortable':false}","{'sClass':'th-name','sTitle':'#{I18n.t :title}'}","{'sTitle':'#{I18n.t :comment, :count => 2}', 'bSearchable':false,'bSortable':false}","{'sTitle':'#{I18n.t :author}', 'bSearchable':false,'bSortable':false}","{'sClass':'th-date','sTitle':'#{I18n.t :updated_at}'}","{'sTitle':'#{I18n.t :status, :count => 1}'}","{'sClass':'actions-td','bSearchable':false,'bSortable':false}"]

app/views/admin/pages/index.json.erb
<%
  output = {
    :sEcho => params[:sEcho],
    :iTotalRecords => @pages.total_entries || 0,
    :iTotalDisplayRecords => @pages.size,
    :aaData => @pages.collect do |page|
      # status = [['published', 'published'], ['draft', 'draft'], ['to validate', 'to-validate']]
      status = [[I18n.t('page.published'), 'published'], [I18n.t('page.draft'), 'draft']]

      if params[:mode] && params[:mode].eql?('menu_link')
        [
          content_tag(:div, content_tag(:div, '',:class=>'handler')+content_tag(:div, '', :class=>'small-icons page'), :id => polymorphic_html_id(page), :class => 'handler_container'),
          content_tag(:div, page.title, :class => 'page-name'),
          page.id,
          link_to(page.title, [forgeos_cms, :admin, page])
        ]
      else
        [
          content_tag(:div, content_tag(:div, '', :class=>'handler')+content_tag(:div, '', :class=>'small-icons page'), :id => polymorphic_html_id(page), :class => 'handler_container'),
          content_tag(:div, link_to(page.title, [forgeos_cms, :admin, page]), :class => 'page-name'),
          '',
          '',
          page.updated_at.to_s,
          select_tag(:status, options_for_select(status, page.active ? 'published' : 'draft'), :class => 'customize published', :onchange => "jQuery.ajax({url: '#{forgeos_cms.activate_admin_page_path(page)}', data: { active: this.value }});"),
          link_to('', [forgeos_cms, :duplicate, :admin, page], :class => 'small-icons duplicate-link') +
          link_to('', [forgeos_cms, :edit, :admin, page], :class => 'small-icons edit-link') +
          link_to('', [forgeos_cms, :admin, page],
            :remote => true,
            :method => 'delete',
            :confirm => I18n.t('page.destroy.confirm').capitalize,
            :class => 'small-icons destroy-link',
            :id => polymorphic_html_id(page, 'destroy')
          )
        ]
      end
    end
  }
-%>
<%= raw output.to_json -%>

app/views/admin/pages/show.html.haml
= render :partial => 'admin/menus/lang_switcher'
= render :partial => 'tabs'
#wrap
  .backgrounds.big-header
    %h1
      = @page.title
    .interact-links
      = link_to t('page.update.action').capitalize, [forgeos_cms, :edit, :admin, @page ], :class => 'backgrounds interact-button'
      = t :or
      = link_to t('page.back').capitalize, forgeos_cms.admin_pages_path, :class => 'back-link'
  #content.grid_16.alpha.omega
    .grid_12.alpha
      .inner-content
        %h2.permalink
          = t(:permalink, :count => 1).capitalize
          \:
          = forgeos_cms.page_url(@page.url)
        .fieldset
          %h2= t :content
          .page-content
            %iframe{ :src => forgeos_cms.page_url(@page.url), :width => '100%', :height => 500, :style => 'border: none' }
        - unless @page.blocks.empty?
          .fieldset
            %h2= t('block', :count => 2)
            - @page.blocks.each do |block|
              %div.block-container
                %span.block-type
                  = block.class.model_name.human.capitalize
                %span.block-name
                  = block.title
    #right-sidebar.grid_4.omega
      .step.status.open
        -# status = [[t('page.published'), 'published'], [t('page.draft'), 'draft'], [t('to validate'), 'to-validate']]
        - status = [[t('page.published'), 'published'], [t('page.draft'), 'draft']]
        = select_tag :status, options_for_select(status, @page.active ? 'published' : 'draft'), :class => 'customize published'
        .clear
        %p
          - unless @page.new_record? or !@page.active or @page.published_at.nil?
            = t('page.published_on').capitalize
            %span.last-date= @page.published_at.to_date
      #pages_show_tags.step.open
        = link_to t('tag', :count => 2).capitalize, '#', :class => 'small-icons step-title'
        .inner-step.tags
          - @page.tags_on(:tags).each do |tag|
            %label= tag.name
      #pages_show_meta.step.open
        = link_to t('page.meta_description').capitalize, '#', :class => 'small-icons step-title'
        .inner-step.meta
          %p
            %span
              = t(:title, :count => 1).capitalize
              \:
            = @page.meta_info.title if @page.meta_info
          %p
            %span
              = t(:description).capitalize
              \:
            = @page.meta_info.description if @page.meta_info
          %p
            %span
              = t(:keyword, :count => 2).capitalize
              \:
            = @page.meta_info.keywords if @page.meta_info
      .step.disabled
        = link_to t(:graphic_template, :count => 1).capitalize, '#', :class => 'small-icons step-title'
        .inner-step.glossy
    .clear