config/routes.rb
Forgeos::Cms::Engine.routes.draw do
  namespace :admin do
    %w(page block).each do |model|
      match "/import/create_#{model}" => "import#create_#{model}", :as => "import_create_#{model}"
    end


    resources :actualities do
      member do
        post :activate
      end
    end
    resources :static_content_blocks do
      member do
        get :duplicate
      end
    end

    resources :blocks, :controller => 'static_content_blocks'

    resources :pages do
      member do
        post :activate
        get :duplicate
      end
      collection do
        post :url
      end
      resources :blocks, :controller => 'static_content_blocks', :except => [:show, :index] do
         member do
           post :link
           delete :unlink
        end
      end
      resources :widgets, :except => [:index]
      resources :wactualities, :except => [:show, :index]
      resources :carousels, :except => [:show, :index]
    end

    resources :newsletters
    # modules and widgets
    resources :widgets, :only => [:index]
    resources :carousels do
      member do
        get :duplicate
      end
    end
    resources :widget_actualities do
      member do
        get :duplicate
      end
    end
    resources :link_page do
      member do
        get :duplicate
      end
    end
    resources :widget_faqs do
      member do
        get :duplicate
      end
    end

    resources :menus do
      member do
        get :duplicate
        post :activate
      end
    end

    # categories
    %w(page static_content widget).each do |category|
      resources "#{category}_categories", :controller => 'categories', :type => "#{category}_category"
    end
  end
end

app/models/block.rb
class Block < ActiveRecord::Base
  translates :title, :content
  scope :in_page, lambda{ |page|
    {
      :joins      => :page_cols,
      :conditions => {:page_cols => {:id => page.page_cols}},
      :select     => "DISTINCT `blocks`.*" # kill duplicates
    }
  }

  validates :title, :presence => true

  has_and_belongs_to_many :page_cols,
    :order => 'position'
  has_and_belongs_to_many :categories,
    :readonly => true,
    :join_table => 'categories_elements',
    :foreign_key => 'element_id',
    :association_foreign_key => 'category_id'

  before_destroy :check_has_no_single_key

  define_index do
    indexes single_key, :sortable => true
  end

  define_translated_index :title, :content

  def clone
    cloned = super
    cloned.translations = translations.clone unless translations.empty?
    %w(page_col_ids category_ids).each do |method|
      cloned.send("#{method}=",self.send(method))
    end
    return cloned
  end

  def pages
    self.page_cols.map(&:page)
  end

  def linked_with?(page)
    self.pages.include?(page)
  end

  def link_with(page)
    page.blocks << self
    page.blocks.reset_positions
  end

  def unlink_with(page)
    page.blocks.delete self
    page.blocks.reset_positions
  end

private

  # if the block contains a single_key, it can not be destroyed
  def check_has_no_single_key
    if !self.single_key.blank?
      errors.add(:single_key, :no_destroy)
      return false
    end
  end
end

app/models/page.rb
class Page < ActiveRecord::Base
  translates :title, :url
  define_translated_index :title, :url
  acts_as_taggable_on :tags

  attr_accessor :page_urls

  validates :title, :url, :presence => true
  validates :single_key, :if => Proc.new {|c| c.single_key}, :uniqueness => true

  has_one :meta_info,
    :as => :target,
    :dependent => :destroy
  accepts_nested_attributes_for :meta_info

  has_many :page_cols,
    :dependent => :destroy
  has_many :blocks,
    :through => :page_cols
  accepts_nested_attributes_for :page_cols

  has_many :viewed_counters,
    :as => :element,
    :class_name => 'PageViewedCounter',
    :dependent => :destroy
  has_many :menu_links,
    :as => :target

  has_and_belongs_to_many :categories,
    :readonly => true,
    :join_table => 'categories_elements',
    :foreign_key => 'element_id',
    :association_foreign_key => 'category_id'
  has_and_belongs_to_many :linked_pages,
    :class_name => 'Page',
    :association_foreign_key => 'linked_page_id',
    :foreign_key => 'page_id',
    :join_table => 'pages_links'

  before_destroy :check_has_no_single_key,
    :keep_page_translated_urls


  def name
    self.title
  end

  def page_urls
    destroyed? ? super : translations.collect(&:url)
  end

  def min_cols_by_page
    1
  end

  def activate
    # set publication date if page changes from inactive to active
    self.published_at = Time.now unless self.active

    # update active status
    self.update_attribute('active', !self.active)
  end

  def clone
    page = super
    page.meta_info = meta_info.clone if meta_info
    page.translations = translations.clone unless translations.empty?
    page.page_cols = page_cols.map(&:clone)
    page.tags = tags
    return page
  end

  private
  # if the page contains a single_key, it can not be destroyed
  def check_has_no_single_key
    unless self.single_key.blank?
      errors.add(:the_page, :has_single_key)
      return false
    end
  end

  def keep_page_translated_urls
    self.page_urls = translations.collect(&:url)
  end
end

app/views/admin/blocks/_associated_pages.html.haml
- unless defined?(level)
  - level = 0
- categories.each do |category|
  %li
    = link_to category.name, '#'
    - unless category.children.empty?
      %ul
        - category.children.each do |child|
          = render :partial => 'admin/blocks/associated_pages', :locals => { :categories => [child], :level => (level + 1), :block => block, :element_id => element_id }
        - category.pages.each do |_page|
          %li{ :type => 'folder'}
            = link_to _page.title, '#'
            %ul
              - _page.page_cols.each_with_index do |page_col, index|
                - checked = block.page_cols.include?(page_col)
                %li{:id => "page_col_#{page_col.id}", :class => checked ? 'jstree-checked' : 'jstree-unchecked' }
                  = link_to t("page_col_#{index}"), '#'
                  - if checked
                    = hidden_field_tag "#{element_id}[page_col_ids][]", page_col.id

- unless !defined?(pages) or pages.empty?
  - pages.each do |page|
    %li
      = link_to page.title, '#'
      - unless page.page_cols.empty?
        %ul
          - page.page_cols.each_with_index do |page_col, index|
            - checked = block.page_cols.include?(page_col)
            %li{:id => "page_col_#{page_col.id}", :class => checked ? 'jstree-checked' : 'jstree-unchecked' }
              = link_to t("page_col_#{index}").capitalize, '#'
              - if checked
                = hidden_field_tag "#{element_id}[page_col_ids][]", page_col.id

app/views/admin/blocks/_form.html.haml
= include_tiny_mce_if_needed
- form_for [:admin, block], :url => (block.new_record? ? admin_blocks_path : admin_block_path(block)), :html => { :method => (block.new_record? ? :post : :put), :multipart => true } do |f|
  = f.error_messages
  %p
    %b
      %label
        = I18n.t('title').capitalize
    = f.text_field :title
  %p
    %b
      %label
        = I18n.t('content').capitalize
    %p
      = link_to_function I18n.t('editor.show.action'), "toggleEditor('block_content',this)"
  = f.text_area :content, :cols => 80
  = hidden_field_tag 'page_id', page_id if defined?(page_id) && !page_id.blank?
  = submit_tag I18n.t('save').capitalize

app/views/admin/blocks/_tabs.html.haml
%ul.ui-tabs-nav.ui-helper-reset.ui-helper-clearfix.ui-widget-header.ui-corner-all
  %li.ui-state-default.ui-corner-top= link_to I18n.t('page', :count => 2).capitalize, [forgeos_cms, :admin, :pages]
  %li.ui-state-default.ui-corner-top.ui-tabs-selected.ui-state-active= link_to I18n.t('block', :count => 2).capitalize, '#content'
  %li.ui-state-default.ui-corner-top= link_to I18n.t('navigation').capitalize, [forgeos_cms, :admin, :menus]
  %li.ui-state-default.ui-corner-top= link_to I18n.t('actuality', :count => 2).capitalize, [forgeos_cms, :admin, :actualities]
#sub-links
  %ul
    %li= link_to I18n.t('static_content_block', :count => 1).capitalize, '#', :class => 'selected'
    %li= link_to I18n.t('widget', :count => 2).capitalize, [forgeos_cms, :admin, :widgets]

app/views/admin/blocks/create.html.erb
<%= render :partial => 'top_links', :locals => { :block => @block } %>

<h1><%= I18n.t('block.create.action').capitalize %></h1>

<%= render :partial => 'form', :locals => { :action => 'create', :block => @block, :page_id => params[:page_id] } %>